version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: my-http-service
    ports:
      - '8080:80'
    environment:
      BACK_URL: backend
   backend:
  backend:
    build: ./backend
    container_name: my-python-service
    ports:
      - '5001:5000'
  mongodb:
    image: mongo:4.0.28-xenial
    container_name: my-db
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
volumes:
  db-data:
